title: [Linked Data Signature Starter Kit]
description:
  [
    The purpose of this repo is to provide a starting point for developers wishing to implement JSON-LD Signatures.,
  ]
# google_analytics: [Your Google Analytics tracking ID]
